name: Generate Snake Animation

on:
  schedule:
    # Atualiza a cobrinha diariamente
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório
      - uses: actions/checkout@v2

      # Configura e gera a cobrinha
      - uses: Platane/snk@v2
        with:
          github_user_name: Nelhapa
          outputs: dist/snake.svg

      # Faz o upload do arquivo gerado
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
